#!/usr/bin/python

"""Amulet tests on a basic swift-proxy deployment on trusty-icehouse."""

from basic_deployment import SwiftProxyBasicDeployment

if __name__ == '__main__':
    deployment = SwiftProxyBasicDeployment(series='trusty')
    deployment.run_tests()
