#!/usr/bin/python

"""Amulet tests on a basic swift-proxy deployment on trusty-juno."""

from basic_deployment import SwiftProxyBasicDeployment

if __name__ == '__main__':
    deployment = SwiftProxyBasicDeployment(series='trusty',
                                        openstack='cloud:trusty-juno',
                                        source='cloud:trusty-updates/juno')
    deployment.run_tests()
