#!/usr/bin/python

"""Amulet tests on a basic swift-proxy deployment on utopic-juno."""

from basic_deployment import SwiftProxyBasicDeployment

if __name__ == '__main__':
    deployment = SwiftProxyBasicDeployment(series='utopic')
    deployment.run_tests()
