#!/usr/bin/python

"""Amulet tests on a basic swift-proxy deployment on trusty-mitaka."""

from basic_deployment import SwiftProxyBasicDeployment

if __name__ == '__main__':
    deployment = SwiftProxyBasicDeployment(series='trusty',
                                        openstack='cloud:trusty-mitaka',
                                        source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
