#!/usr/bin/python

"""Amulet tests on a basic swift-proxy deployment on trusty-liberty."""

from basic_deployment import SwiftProxyBasicDeployment

if __name__ == '__main__':
    deployment = SwiftProxyBasicDeployment(series='trusty',
                                        openstack='cloud:trusty-liberty',
                                        source='cloud:trusty-updates/liberty')
    deployment.run_tests()
