#!/usr/bin/python

"""Amulet tests on a basic swift-proxy deployment on xenial-mitaka."""

from basic_deployment import SwiftProxyBasicDeployment

if __name__ == '__main__':
    deployment = SwiftProxyBasicDeployment(series='xenial')
    deployment.run_tests()
