#!/usr/bin/python

"""Amulet tests on a basic swift-proxy deployment on precise-essex."""

from basic_deployment import SwiftProxyBasicDeployment

if __name__ == '__main__':
    deployment = SwiftProxyBasicDeployment(series='precise')
    deployment.run_tests()
