#!/usr/bin/python

"""Amulet tests on a basic swift-proxy deployment on precise-folsom."""

from basic_deployment import SwiftProxyBasicDeployment

if __name__ == '__main__':
    deployment = SwiftProxyBasicDeployment(series='precise',
                                          openstack='cloud:precise-folsom',
                                          source='cloud:precise-updates/folsom')
    deployment.run_tests()
