#!/usr/bin/python

"""Amulet tests on a basic swift-proxy deployment on precise-grizzly."""

from basic_deployment import SwiftProxyBasicDeployment

if __name__ == '__main__':
    deployment = SwiftProxyBasicDeployment(series='precise',
                                         openstack='cloud:precise-grizzly',
                                         source='cloud:precise-updates/grizzly')
    deployment.run_tests()
