#!/usr/bin/python

"""Amulet tests on a basic swift-proxy deployment on precise-icehouse."""

from basic_deployment import SwiftProxyBasicDeployment

if __name__ == '__main__':
    deployment = SwiftProxyBasicDeployment(series='precise',
                                        openstack='cloud:precise-icehouse',
                                        source='cloud:precise-updates/icehouse')
    deployment.run_tests()
